#
# fetch .rpm or .tar.gz files
#

- name: get JDK tarball (as RPM file)
  get_url:
    url:     "{{ jdk_tarball_url }}.rpm"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest:    "{{ java_download_path }}/{{ jdk_tarball_file }}.rpm"
  when: (ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "zypper") and ansible_os_family != 'Darwin'


- name: get JDK tarball (as tar.gz file)
  get_url:
    url:     "{{ jdk_tarball_url }}.tar.gz"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest:    "{{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz"
  when: ansible_pkg_mgr != "yum" or ansible_pkg_mgr != "zypper" and ansible_os_family != 'Darwin'

- name: get JDK package (as Mac OS X .dmg)
  get_url:
    url:     "{{ jdk_tarball_url }}.dmg"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest:    "{{ java_download_path }}/{{ jdk_tarball_file }}.dmg"
  when: ansible_os_family == 'Darwin'

- name: get JCE
  get_url:
    url:     "{{ jce_zip_url }}"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest:    "{{ java_download_path }}/{{ jce_zip_file }}"
  when: java_install_jce
