#
# install Oracle JDK 1.x on distributions other than the CentOS/RHEL family
#
# See: http://docs.oracle.com/javase/8/docs/technotes/guides/install/linux_jdk.html
#

- name: get JDK tarball (as tar.gz file)
  command: curl -L  -H 'Cookie:oraclelicense=accept-securebackup-cookie'  -o {{ jdk_tarball_file }}.tar.gz  {{ jdk_tarball_url }}.tar.gz
  args:
    creates: "{{ java_download_path }}/jdk-tarball-{{ jdk_version }}"
    chdir:   "{{ java_download_path }}"

- name: mkdir for Java
  file:
    path: "/usr/java/jdk{{ jdk_version }}"
    state: directory
    owner: root
    group: root
    mode: "u=rwx,go=rx"

- name: install JDK
  unarchive:
    src: "{{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz"
    dest: "/usr/java"
    owner: root
    group: root
    mode: "go-w"
    copy: no
