---
# file: tasks/set-role-variables.yml
# set necessary role variables.
#


- name: set general internal vars
  set_fact:
    jdk_version: "1.{{ java_version }}.0_{{ java_subversion }}"


#
# platform-specific variables
#

- name: set java architecture
  set_fact:
    jdk_arch: "{{ 'i586'  if ansible_architecture == 'i386' else 'x64' }}"

- name: set java OS for Linux
  set_fact:
    jdk_os: linux
  when: ansible_system == 'Linux'

- name: set java OS for Mac OS X
  set_fact:
    jdk_os: macosx
  when: ansible_os_family == 'Darwin'


#
# version-specific variables
#

- name: set internal vars for 1.8.0_77
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b03"
  when: java_version == 8 and java_subversion == 77

- name: set internal vars for 1.8.0_74
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b02"
  when: java_version == 8 and java_subversion == 74

- name: set internal vars for 1.8.0_73
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b02"
  when: java_version == 8 and java_subversion == 73

- name: set internal vars for 1.8.0_72
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b15"
  when: java_version == 8 and java_subversion == 72

- name: set internal vars for 1.8.0_66
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b17"
  when: java_version == 8 and java_subversion == 66

- name: set internal vars for 1.8.0_65
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b17"
  when: java_version == 8 and java_subversion == 65

- name: set internal vars for 1.8.0_60
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b27"
  when: java_version == 8 and java_subversion == 60

- name: set internal vars for 1.8.0_51
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b16"
  when: java_version == 8 and java_subversion == 51

- name: set internal vars for 1.8.0_45
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b14"
  when: java_version == 8 and java_subversion == 45

- name: set internal vars for 1.8.0_31
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b13"
  when: java_version == 8 and java_subversion == 31

- name: set internal vars for 1.7.0_80
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b15"
  when: java_version == 7 and java_subversion == 80

- name: set internal vars for 1.7.0_75
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b13"
  when: java_version == 7 and java_subversion == 75



- name: compose filename, if necessary
  set_fact:
    jdk_tarball_file: "jdk-{{ java_version }}u{{ java_subversion }}-{{ jdk_os }}-{{ jdk_arch }}"
  when: jdk_tarball_file is not defined

- name: compose url for downloading file, if necessary
  set_fact:
    jdk_tarball_url:  "http://download.oracle.com/otn-pub/java/jdk/{{ jdk_version_detail }}/{{ jdk_tarball_file }}"
  when: jdk_version_detail is defined


#
# JCE variables
#

- name: set JCE variables
  set_fact:
    jce_zip_file:   "jce_policy-{{ java_version }}.zip"
    jce_zip_folder: "UnlimitedJCEPolicyJDK{{ java_version }}"

- name: set JCE download file
  set_fact:
    jce_zip_url: "http://download.oracle.com/otn-pub/java/jce/{{ java_version }}/{{ jce_zip_file }}"


#
# directories
#

- name: set java installation directory on Debian platforms
  set_fact:
    java_install_dir: /usr/lib/jvm
    java_default_link_name: default-java
  when: ansible_os_family == "Debian"

- name: set java installation directory on Mac OS X
  set_fact:
    # The Java installation directory on Mac OS X is determined by the package itself.
    java_install_dir: /no_such_directory
    java_default_link_name: default
  when: ansible_os_family == "Darwin"

- name: set java installation directory on non-Debian platforms
  set_fact:
    java_install_dir: /usr/java
    java_default_link_name: default
  when: ansible_os_family != "Debian" and ansible_os_family != "Darwin"
