---
# file: tasks/set-role-variables.yml
# set necessary role variables.
#

- name: set internal vars for 1.8.0_65
  set_fact:
    jdk_version:      1.8.0_65
    jdk_tarball_file: jdk-8u65-linux-x64
    jdk_tarball_url:  http://download.oracle.com/otn-pub/java/jdk/8u65-b17/jdk-8u65-linux-x64
  when: java_version == 8 and java_subversion == 65

- name: set internal vars for 1.8.0_60
  set_fact:
    jdk_version:      1.8.0_60
    jdk_tarball_file: jdk-8u60-linux-x64
    jdk_tarball_url:  http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64
  when: java_version == 8 and java_subversion == 60

- name: set internal vars for 1.8.0_51
  set_fact:
    jdk_version:      1.8.0_51
    jdk_tarball_file: jdk-8u51-linux-x64
    jdk_tarball_url:  http://download.oracle.com/otn-pub/java/jdk/8u51-b16/jdk-8u51-linux-x64
  when: java_version == 8 and java_subversion == 51

- name: set internal vars for 1.8.0_45
  set_fact:
    jdk_version:      1.8.0_45
    jdk_tarball_file: jdk-8u45-linux-x64
    jdk_tarball_url:  http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jdk-8u45-linux-x64
  when: java_version == 8 and java_subversion == 45

- name: set internal vars for 1.8.0_31
  set_fact:
    jdk_version:      1.8.0_31
    jdk_tarball_file: jdk-8u31-linux-x64
    jdk_tarball_url:  http://download.oracle.com/otn-pub/java/jdk/8u31-b13/jdk-8u31-linux-x64
  when: java_version == 8 and java_subversion == 31




- name: set internal vars for 1.7.0_80
  set_fact:
    jdk_version:      1.7.0_80
    jdk_tarball_file: jdk-7u80-linux-x64
    jdk_tarball_url:  http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64
  when: java_version == 7 and java_subversion == 80

- name: set internal vars for 1.7.0_75
  set_fact:
    jdk_version:      1.7.0_75
    jdk_tarball_file: jdk-7u75-linux-x64
    jdk_tarball_url:  http://download.oracle.com/otn-pub/java/jdk/7u75-b13/jdk-7u75-linux-x64
  when: java_version == 7 and java_subversion == 75
